"""averageRates table

Revision ID: 45f1f2e15163
Revises: 
Create Date: 2024-03-21 10:00:59.210984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f1f2e15163'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('averageRates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('averageRates')
    # ### end Alembic commands ###
